import { askNurjahanAI, createSupportTicket } from './ai-support.js';

const styles = `
#nj-ai-launch{position:fixed;right:18px;bottom:18px;z-index:9999;border:0;border-radius:999px;padding:14px 18px;background:linear-gradient(135deg,#2563eb,#7c3aed);color:#fff;font-weight:900;box-shadow:0 12px 30px #0003;cursor:pointer}
#nj-ai-panel{position:fixed;right:18px;bottom:78px;width:min(390px,calc(100vw - 28px));height:min(610px,calc(100vh - 105px));z-index:9998;background:#fff;border:1px solid #dbe3ef;border-radius:22px;box-shadow:0 22px 70px #0004;display:none;overflow:hidden}
#nj-ai-head{background:linear-gradient(135deg,#111827,#2563eb);color:#fff;padding:16px;display:flex;justify-content:space-between;align-items:center}
#nj-ai-head b{font-size:17px}#nj-ai-close{border:0;background:#ffffff22;color:#fff;border-radius:9px;padding:7px 10px;cursor:pointer}
#nj-ai-body{height:calc(100% - 132px);overflow:auto;padding:12px;background:#f8fafc}
.nj-msg{max-width:88%;padding:10px 12px;border-radius:15px;margin:8px 0;line-height:1.5;white-space:pre-wrap;font-size:14px}.nj-user{margin-left:auto;background:#2563eb;color:#fff;border-bottom-right-radius:5px}.nj-bot{background:#fff;border:1px solid #e2e8f0;border-bottom-left-radius:5px}.nj-quick{display:flex;gap:7px;flex-wrap:wrap;margin:5px 0 12px}.nj-quick button{border:1px solid #bfdbfe;background:#eff6ff;color:#1d4ed8;border-radius:999px;padding:7px 10px;cursor:pointer;font-size:12px;font-weight:750}
#nj-ai-form{display:flex;gap:7px;padding:10px;border-top:1px solid #e2e8f0;background:#fff}#nj-ai-input{min-width:0;flex:1;padding:11px;border:1px solid #cbd5e1;border-radius:12px;font-size:15px}#nj-ai-send{border:0;border-radius:12px;background:#2563eb;color:#fff;padding:0 15px;font-weight:900;cursor:pointer}.nj-tools{padding:6px 10px 0;background:#fff;font-size:11px;color:#64748b}
`;
const style = document.createElement('style'); style.textContent = styles; document.head.appendChild(style);
const panel = document.createElement('section'); panel.id='nj-ai-panel'; panel.innerHTML=`<header id="nj-ai-head"><div>🤖 Nurjahan AI Support<br><small>সব গ্রাহকের জন্য সহায়তা</small></div><button id="nj-ai-close">✕</button></header><div id="nj-ai-body"><div class="nj-msg nj-bot">আসসালামু আলাইকুম! 👋 আমি Nurjahan AI Support। Website, Plan, Payment, Domain, Hosting বা সাধারণ সমস্যায় সাহায্য করতে পারি।</div><div class="nj-quick"><button data-q="Free ও Premium Plan কী?">💎 Plan</button><button data-q="Premium-এর দাম কত এবং কীভাবে payment করব?">💳 Payment</button><button data-q="আমার Website কীভাবে তৈরি করব?">🌐 Website</button><button data-q="Domain ও Hosting সম্পর্কে বলুন।">🚀 Domain/Hosting</button></div></div><div class="nj-tools">সমাধান না হলে AI Admin Review-এর জন্য ticket তৈরি করতে পারবে।</div><form id="nj-ai-form"><input id="nj-ai-input" autocomplete="off" placeholder="আপনার প্রশ্ন লিখুন..."/><button id="nj-ai-send">পাঠান</button></form>`;
document.body.appendChild(panel);
const launch=document.createElement('button'); launch.id='nj-ai-launch'; launch.textContent='🤖 AI Help'; document.body.appendChild(launch);
const body=panel.querySelector('#nj-ai-body'), input=panel.querySelector('#nj-ai-input');
function add(text,who='bot'){const d=document.createElement('div');d.className=`nj-msg nj-${who}`;d.textContent=text;body.appendChild(d);body.scrollTop=body.scrollHeight}
async function ask(text){const q=text.trim();if(!q)return;add(q,'user');input.value='';add('⏳ উত্তর তৈরি করছি...','bot');const pending=body.lastElementChild;try{const answer=await askNurjahanAI(q,JSON.parse(sessionStorage.getItem('njAiHistory')||'[]'));pending.remove();add(answer,'bot');const h=JSON.parse(sessionStorage.getItem('njAiHistory')||'[]');h.push({role:'user',text:q},{role:'model',text:answer});sessionStorage.setItem('njAiHistory',JSON.stringify(h.slice(-12)))}catch(e){pending.textContent='দুঃখিত, এখন AI উত্তর দিতে পারছে না। চাইলে এই সমস্যাটি Admin Review-এর জন্য পাঠাতে পারেন।';const b=document.createElement('button');b.className='nj-quick';b.innerHTML='<button>🆘 Admin Review</button>';b.querySelector('button').onclick=async()=>{try{const id=await createSupportTicket(q,JSON.parse(sessionStorage.getItem('njAiHistory')||'[]'),{page:location.pathname});add(`✅ Support Ticket তৈরি হয়েছে। ID: ${id}`,'bot')}catch(err){add('❌ Ticket তৈরি হয়নি। পরে আবার চেষ্টা করুন।','bot')}};body.appendChild(b);}}
launch.onclick=()=>{panel.style.display='block';input.focus()};panel.querySelector('#nj-ai-close').onclick=()=>panel.style.display='none';panel.querySelector('#nj-ai-form').onsubmit=e=>{e.preventDefault();ask(input.value)};panel.querySelectorAll('.nj-quick button').forEach(b=>b.onclick=()=>ask(b.dataset.q));
