(function(){
  const EXTRA=[['search','🔎','Search'],['notifications','🔔','Alerts'],['account','👤','Account'],['cart','🛒','Cart'],['help','❓','Help']];
  function mount(){
    const panel=document.getElementById('nj-quick-panel'); if(!panel||panel.dataset.extraReady)return; panel.dataset.extraReady='1';
    const css=document.createElement('style');css.textContent='.nj-extra-item{position:fixed;width:40px;height:40px;border-radius:50%;border:1px solid color-mix(in srgb,var(--nj-a,#2563eb) 35%,#cbd5e1);background:color-mix(in srgb,var(--nj-card,#fff) 96%,transparent);color:var(--nj-a,#2563eb);box-shadow:0 7px 18px #0003;display:flex;align-items:center;justify-content:center;flex-direction:column;font:900 13px system-ui,"Noto Sans Bengali",sans-serif;opacity:0;pointer-events:none;transform:scale(.3);transition:.28s cubic-bezier(.34,1.56,.64,1);z-index:10062}.nj-extra-item small{font-size:5px;line-height:1}.nj-extra-open .nj-extra-item{opacity:1;pointer-events:auto;transform:translate(var(--x),var(--y)) scale(1)}.nj-extra-view{position:fixed;right:55px;bottom:52px;width:min(285px,calc(100vw - 65px));max-height:60vh;overflow:auto;padding:12px;border:1px solid color-mix(in srgb,var(--nj-a,#2563eb) 35%,#cbd5e1);border-radius:15px;background:var(--nj-card,#fff);color:var(--text-primary,#111);box-shadow:0 16px 40px #0004;z-index:10063;font:700 12px system-ui,"Noto Sans Bengali",sans-serif}.nj-extra-view[hidden]{display:none}.nj-extra-view h3{margin:0 0 8px;color:var(--nj-a,#2563eb)}.nj-extra-view button{border:1px solid var(--nj-a,#2563eb);background:var(--nj-soft,#f8fafc);color:var(--nj-a,#2563eb);border-radius:8px;padding:7px;margin:3px;font-weight:800}.nj-extra-view input{width:100%;box-sizing:border-box;padding:9px;border:1px solid #cbd5e1;border-radius:8px}@media(max-width:520px){.nj-extra-item{width:37px;height:37px;font-size:12px}.nj-extra-view{right:48px;bottom:48px;width:min(270px,calc(100vw - 58px))}}';document.head.appendChild(css);
    const view=document.createElement('div');view.className='nj-extra-view';view.hidden=true;document.body.appendChild(view);
    EXTRA.forEach((a,i)=>{const b=document.createElement('button');b.type='button';b.className='nj-extra-item';b.innerHTML=`<span>${a[1]}</span><small>${a[2]}</small>`;const angle=Math.PI*.10+Math.PI*.80*i/(EXTRA.length-1),r=175;b.style.setProperty('--x',`${-Math.cos(angle)*r}px`);b.style.setProperty('--y',`${-Math.sin(angle)*r}px`);panel.appendChild(b);b.onclick=()=>show(a[0],a[2]);});
    const fab=document.getElementById('nj-quick-fab'); if(fab)fab.addEventListener('click',()=>panel.classList.toggle('nj-extra-open',!panel.hidden));
    function show(key,title){const close='<button id="nj-extra-close" style="float:right;border-radius:50%;width:26px;height:26px">×</button>';const map={search:'<h3>🔎 Search</h3><p>দ্রুত খুঁজুন</p><input id="nj-search" placeholder="Search..."/><div id="nj-search-out">কী খুঁজছেন লিখুন।</div>',notifications:'<h3>🔔 Notifications</h3><p>Payment, Support ও গুরুত্বপূর্ণ আপডেট এখানে দেখা যাবে।</p><button id="nj-read">✓ সব পড়া হয়েছে</button>',account:'<h3>👤 Account</h3><p>Profile, Privacy ও Account settings এই মেনু থেকেই পরিচালনা করুন।</p><button>⚙️ Settings</button>',cart:'<h3>🛒 Cart</h3><p>আপনার Cart এখন খালি।</p>',help:'<h3>❓ Help Center</h3><p>FAQ, ব্যবহার নির্দেশিকা, Security এবং Support সহায়তা।</p><button id="nj-help-ai">🤖 AI Help</button>'};view.innerHTML=close+(map[key]||`<h3>${title}</h3>`);view.hidden=false;document.getElementById('nj-extra-close').onclick=()=>view.hidden=true;if(key==='search')document.getElementById('nj-search').oninput=e=>document.getElementById('nj-search-out').textContent=e.target.value?`“${e.target.value}” খোঁজা হচ্ছে...`:'কী খুঁজছেন লিখুন।';if(key==='notifications')document.getElementById('nj-read').onclick=()=>document.getElementById('nj-read').textContent='✓ Done';if(key==='help')document.getElementById('nj-help-ai').onclick=()=>view.innerHTML=close+'<h3>🤖 AI Help</h3><p>AI Support প্রস্তুত। আপনার প্রশ্ন লিখুন।</p><input placeholder="প্রশ্ন লিখুন..."/>';}
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,250));else setTimeout(mount,250);
})();
