(function(){
  const GLOBAL_LANGS=[['bn','বাংলা'],['en','English'],['hi','हिन्दी'],['ur','اردو'],['ar','العربية'],['fa','فارسی'],['ps','پښتو'],['ne','नेपाली'],['si','සිංහල'],['ta','தமிழ்'],['te','తెలుగు'],['ml','മലയാളം'],['kn','ಕನ್ನಡ'],['mr','मराठी'],['gu','ગુજરાતી'],['pa','ਪੰਜਾਬੀ'],['as','অসমীয়া'],['or','ଓଡ଼ିଆ'],['th','ไทย'],['vi','Tiếng Việt'],['id','Bahasa Indonesia'],['ms','Bahasa Melayu'],['tl','Filipino'],['zh-CN','简体中文'],['zh-TW','繁體中文'],['ja','日本語'],['ko','한국어'],['tr','Türkçe'],['he','עברית'],['fa','فارسی'],['ru','Русский'],['uk','Українська'],['pl','Polski'],['cs','Čeština'],['sk','Slovenčina'],['hu','Magyar'],['ro','Română'],['bg','Български'],['sr','Српски'],['hr','Hrvatski'],['sl','Slovenščina'],['de','Deutsch'],['fr','Français'],['es','Español'],['pt','Português'],['it','Italiano'],['nl','Nederlands'],['sv','Svenska'],['no','Norsk'],['da','Dansk'],['fi','Suomi'],['el','Ελληνικά'],['et','Eesti'],['lv','Latviešu'],['lt','Lietuvių'],['is','Íslenska'],['ga','Gaeilge'],['sw','Kiswahili'],['am','አማርኛ'],['so','Soomaali'],['ha','Hausa'],['yo','Yorùbá'],['zu','isiZulu'],['af','Afrikaans'],['km','ខ្មែរ'],['lo','ລາວ'],['my','မြန်မာ'],['mn','Монгол'],['ka','ქართული'],['hy','Հայերեն'],['az','Azərbaycan'],['kk','Қазақша'],['uz','O‘zbek'],['tg','Тоҷикӣ'],['tk','Türkmençe'],['ku','Kurdî'],['sq','Shqip'],['mk','Македонски'],['bs','Bosanski'],['eu','Euskara'],['ca','Català'],['gl','Galego'],['cy','Cymraeg'],['eo','Esperanto'],['la','Latina'],['jv','Basa Jawa'],['ceb','Cebuano'],['hmn','Hmong']];
  const COUNTRIES=[['BD','🇧🇩','Bangladesh','বাংলা'],['IN','🇮🇳','India','हिन्दी'],['PK','🇵🇰','Pakistan','اردو'],['SA','🇸🇦','Saudi Arabia','العربية'],['AE','🇦🇪','United Arab Emirates','العربية'],['MY','🇲🇾','Malaysia','Bahasa Melayu'],['ID','🇮🇩','Indonesia','Bahasa Indonesia'],['TR','🇹🇷','Türkiye','Türkçe'],['FR','🇫🇷','France','Français'],['DE','🇩🇪','Germany','Deutsch'],['ES','🇪🇸','Spain','Español'],['JP','🇯🇵','Japan','日本語'],['CN','🇨🇳','China','中文'],['US','🇺🇸','United States','English']];
  const LANGS={BD:[['bn','বাংলা'],['en','English']],IN:[['hi','हिन्दी'],['en','English']],PK:[['ur','اردو'],['en','English']],SA:[['ar','العربية'],['en','English']],AE:[['ar','العربية'],['en','English']],MY:[['ms','Bahasa Melayu'],['en','English']],ID:[['id','Bahasa Indonesia'],['en','English']],TR:[['tr','Türkçe'],['en','English']],FR:[['fr','Français'],['en','English']],DE:[['de','Deutsch'],['en','English']],ES:[['es','Español'],['en','English']],JP:[['ja','日本語'],['en','English']],CN:[['zh','中文'],['en','English']],US:[['en','English']]};
  function loadGlobalTranslator(){
    if(window.google&&window.google.translate)return;
    if(document.getElementById('nj-google-translate-script'))return;
    window.googleTranslateElementInit=function(){
      if(window.google&&google.translate)new google.translate.TranslateElement({pageLanguage:'bn',autoDisplay:false},'nj-google-translate');
    };
    const holder=document.createElement('div');holder.id='nj-google-translate';holder.style.cssText='position:fixed;left:-9999px;top:-9999px;z-index:-1';document.body.appendChild(holder);
    const script=document.createElement('script');script.id='nj-google-translate-script';script.async=true;script.defer=true;script.src='https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';document.head.appendChild(script);
  }
  function globalTranslate(code){
    if(code==='bn'){document.cookie='googtrans=/bn/bn;path=/';document.cookie='googtrans=/bn/bn;path=/;domain='+location.hostname;location.reload();return;}
    loadGlobalTranslator();
    const trySelect=()=>{const sel=document.querySelector('.goog-te-combo');if(!sel)return false;const opt=[...sel.options].find(o=>o.value===code);if(!opt)return false;sel.value=code;sel.dispatchEvent(new Event('change'));document.cookie='googtrans=/bn/'+code+';path=/';return true;};
    let n=0;const timer=setInterval(()=>{if(trySelect()||++n>50)clearInterval(timer)},200);
  }
  function mount(){
    const panel=document.getElementById('nj-quick-panel'),fab=document.getElementById('nj-quick-fab');
    if(!panel||!fab||panel.dataset.localeReady)return; panel.dataset.localeReady='1';
    const css=document.createElement('style');css.textContent=`.nj-locale-item{position:fixed;width:42px;height:42px;border-radius:50%;border:1px solid color-mix(in srgb,var(--nj-a,#2563eb) 35%,#cbd5e1);background:var(--nj-card,#fff);color:var(--nj-a,#2563eb);box-shadow:0 7px 18px #0003;display:flex;align-items:center;justify-content:center;flex-direction:column;font:900 14px system-ui,'Noto Sans Bengali',sans-serif;opacity:0;pointer-events:none;transform:scale(.25);transition:.3s cubic-bezier(.34,1.56,.64,1);z-index:10064}.nj-locale-item small{font-size:5.5px;line-height:1}.nj-locale-open .nj-locale-item{opacity:1;pointer-events:auto;transform:translate(var(--x),var(--y)) scale(1)}.nj-locale-view{position:fixed;right:58px;bottom:54px;width:min(300px,calc(100vw - 70px));max-height:62vh;overflow:auto;padding:12px;border:1px solid color-mix(in srgb,var(--nj-a,#2563eb) 35%,#cbd5e1);border-radius:16px;background:var(--nj-card,#fff);color:var(--text-primary,#111);box-shadow:0 16px 45px #0004;z-index:10065;font:700 12px system-ui,'Noto Sans Bengali',sans-serif}.nj-locale-view[hidden]{display:none}.nj-locale-view h3{margin:0 0 8px;color:var(--nj-a,#2563eb)}.nj-locale-view button{width:100%;padding:8px;margin:3px 0;border:1px solid var(--nj-a,#2563eb);border-radius:8px;background:var(--nj-soft,#f8fafc);color:var(--nj-a,#2563eb);font-weight:800;text-align:left}.nj-locale-view .selected{outline:2px solid var(--nj-a,#2563eb)}.nj-locale-close{float:right!important;width:28px!important;border-radius:50%!important;text-align:center!important;padding:4px!important;background:var(--nj-a,#2563eb)!important;color:#fff!important}@media(max-width:520px){.nj-locale-item{width:38px;height:38px;font-size:13px}.nj-locale-view{right:50px;bottom:50px;width:min(275px,calc(100vw - 60px))}}`;document.head.appendChild(css);
    const add=(key,icon,label,index)=>{const b=document.createElement('button');b.type='button';b.className='nj-locale-item';b.innerHTML=`<span>${icon}</span><small>${label}</small>`;const angle=Math.PI*.25+Math.PI*.5*index;const r=175;b.style.setProperty('--x',`${-Math.cos(angle)*r}px`);b.style.setProperty('--y',`${-Math.sin(angle)*r}px`);panel.appendChild(b);b.onclick=()=>show(key)};
    const actions=panel.querySelector('.nj-q-actions');
    const languageHost=actions||panel;
    if(languageHost&&!languageHost.querySelector('#nj-language-menu-btn')){
      const languageBtn=document.createElement('button');languageBtn.type='button';languageBtn.id='nj-language-menu-btn';languageBtn.dataset.locale='language';languageBtn.textContent='🗣️ Language';
      languageHost.appendChild(languageBtn);
      languageBtn.onclick=(e)=>{e.preventDefault();e.stopPropagation();show('language-settings')};
    }
    const view=document.createElement('div');view.className='nj-locale-view';view.hidden=true;document.body.appendChild(view);
    function show(key){const country=localStorage.getItem('njCountry')||'BD',lang=localStorage.getItem('njLanguage')||'bn';const close='<button class="nj-locale-close" aria-label="Close">×</button>';if(key==='language-settings'){view.innerHTML=close+'<h3>🌐 Country & 🗣️ Language</h3><p>নিচ থেকে Country বা Language নির্বাচন করুন।</p><button type="button" id="nj-open-country">🌍 Country Select</button><button type="button" id="nj-open-language">🗣️ Language Select</button>';view.hidden=false;view.querySelector('#nj-open-country').onclick=()=>show('country');view.querySelector('#nj-open-language').onclick=()=>show('language')}else if(key==='country'){view.innerHTML=close+'<h3>🌍 Country</h3><p>দেশ নির্বাচন করলে ঐ দেশের ভাষা + English দেখাবে।</p><div id="nj-country-list"></div>';const g=view.querySelector('#nj-country-list');COUNTRIES.forEach(([c,f,n,l])=>{const b=document.createElement('button');b.className=c===country?'selected':'';b.innerHTML=`${f} ${n} <span style="float:right">${l}</span>`;b.onclick=()=>{localStorage.setItem('njCountry',c);const list=LANGS[c]||[['en','English']];const keep=list.some(x=>x[0]===lang)?lang:list[0][0];localStorage.setItem('njLanguage',keep);applyLang(keep);show('language')};g.appendChild(b)})}else{view.innerHTML=close+'<h3>🗣️ Language</h3><p>Current country: '+country+'</p><p style="font-size:11px;color:#64748b">🌍 Global language mode — 80+ languages</p><div id="nj-language-list"></div>';const g=view.querySelector('#nj-language-list');GLOBAL_LANGS.forEach(([code,name])=>{const b=document.createElement('button');b.className=code===lang?'selected':'';b.textContent=(code==='en'?'🇬🇧 ':'🌐 ')+name;b.onclick=()=>{localStorage.setItem('njLanguage',code);applyLang(code);view.hidden=true;view.setAttribute('data-selected-language',code)};g.appendChild(b)})}view.hidden=false;view.querySelector('.nj-locale-close').onclick=()=>view.hidden=true}
    function applyLang(code){document.documentElement.lang=code;document.documentElement.dir=['ar','ur','fa','he'].includes(code)?'rtl':'ltr';if(typeof window.nurjahanTranslate==='function')window.nurjahanTranslate(code);window.dispatchEvent(new CustomEvent('nurjahan:languagechange',{detail:{language:code,country:localStorage.getItem('njCountry')||'BD'}}));if(!['bn','en'].includes(code))globalTranslate(code)}
    const saved=localStorage.getItem('njLanguage');if(saved)applyLang(saved);
    fab.addEventListener('click',()=>panel.classList.toggle('nj-locale-open',!panel.hidden));
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,250));else setTimeout(mount,250);
})();
